[book]
authors = ["CHIKASOFT"]
language = "en"
multilingual = false
src = "src"
title = "Unofficial RPG Maker 2000/2003 Specifications"
description = "Unofficial specifications for the RPG Maker 2000/2003 editors and runtimes."

[build]
create-missing = false

[rust]
edition = "2018"
