[book]
authors = ["CHIKASOFT"]
language = "en"
multilingual = false
src = "src"
title = "Unofficial RPG Maker 2000/2003 Specifications"
description = "Unofficial specifications for the RPG Maker 2000/2003 editors and runtimes."

[preprocessor.links]
[preprocessor.index]

[output.html]
curly-quotes = true
default-theme = "navy"
git-repository-url = "https://github.com/chikasoft/RPG-Maker-Specifications"

[output.html.fold]
enable = true
level = 0

[build]
create-missing = false

[rust]
edition = "2018"
